[package]
name = "jubilant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3"
egui-macroquad = "0.7"
tinyfiledialogs = "3.8"
include_dir = "0.7"
enumflags2 = "0.7"
